#!/bin/bash
clear
filename="compile"
clean(){
	echo -e "\n------------------------------------" 
	echo    ":::: Clean ::::" 
	echo -e "------------------------------------\n" 
}

compile(){
	echo -e "\n------------------------------------" 
	echo 	":::: Compile ::::" 
	echo -e "------------------------------------\n" 

	flex -d --nounistd -oscannerRule.yy.cpp scannerRule.l
	bison -d -oparserRule.tab.cpp parserRule.y

	g++ -c scannerRule.yy.cpp -o scannerRule.yy.obj
	g++ -c AST.cpp -o AST.obj
	g++ -c parserRule.tab.cpp -o parserRule.tab.obj
	g++ -o $filename compiler.cpp parserRule.tab.obj scannerRule.yy.obj AST.obj
	echo -e "------------------------------------\n" 
}

run(){
	echo $filename
	echo -e "\n------------------------------------" 
	echo 	":::: RUN ::::" 
	echo -e "------------------------------------\n" 
	echo "/****** Start Process ******/"

	./$filename AddressBookTest1.txt
	
	echo "/****** End Process ******/"
	
}

while [ $# -gt 0 ]
do
    case "$1" in
    	-o)  
			filename=$2; shift ;;
        clean)  
			clean ;;
        compile)  
			compile;;
        run)  
			run;;
 		*)  
	      echo "`basename ${0}`:usage: [-o file name] | [clean] | [compile] | [run]"
	      exit 1 # Command to come out of the program with status 1
	      ;; 
    esac
    shift
done



